---

namespace: bdbstudios
name: openshift_bootstrap
version: 1.0.0
readme: README.md
authors:
  - Brett Minnie <brett@bdb-studios.co.uk>
description: Ansible collection to bootstrap an Openshift Cluster
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - linux
  - infrastructure
dependencies: {}
repository: https://github.com/BDB-Studios/ansible-openshift-bootstrap-collection
documentation: https://github.com/BDB-Studios/ansible-openshift-bootstrap-collection
homepage: https://github.com/BDB-Studios/ansible-openshift-bootstrap-collection
issues: https://github.com/BDB-Studios/ansible-openshift-bootstrap-collection/issues
build_ignore: []

...
