---

- name: Restart Dns Service
  ansible.builtin.systemd:
    name: "{{ bind.service }}"
    state: restarted
    daemon_reload: true

- name: Enable and Start DNS Service
  ansible.builtin.systemd:
    name: "{{ bind.service }}"
    enabled: true
    state: started
    daemon_reload: true

- name: Reload Firewall
  ansible.builtin.command:
    cmd: "firewall-cmd --reload"
  failed_when: false
  changed_when: true

- name: Stop dns service
  ansible.builtin.systemd:
    name: "{{ bind.service }}"
    enabled: false
    state: stopped

...
