---

- name: Create our ignition files
  ansible.builtin.include_tasks: ignition_files.yml

- name: Install TFPT packages
  ansible.builtin.include_tasks: tftp_packages.yml
  tags:
    - tftpd

- name: Manager our local ftp user and group
  ansible.builtin.include_tasks: tftp_user.yml
  tags:
    - tftpd

- name: Configure tftp service
  ansible.builtin.include_tasks: tftp_service.yml
  tags:
    - tftpd

- name: Manage HTTPD packages
  ansible.builtin.include_tasks: httpd_packages.yml
  tags:
    - httpd

- name: Manage HTTPD users
  ansible.builtin.include_tasks: httpd_users.yml
  tags:
    - httpd

- name: Configure HTTPD service
  ansible.builtin.include_tasks: httpd_service.yml
  tags:
    - httpd

...
