---

- name: Ensure we have bash completion supported
  ansible.builtin.dnf:
    name: "bash-completion"
    state: present

- name: Ensure our completion scripts are in the global bashrc
  ansible.builtin.blockinfile:
    path: /etc/bashrc
    block: |
      source <(oc completion bash)
      source <(kubectl completion bash)
    insertafter: ""
  tags:
    - always

- name: Ensure we have our environment config file
  when: define_oc_env | default(false) | bool
  ansible.builtin.template:
    dest: "/root/.oc_env.sh"
    src: ./templates/oc_env.sh.j2
    owner: root
    group: root
    mode: 0644
  tags:
    - always

- name: Ensure that we source our env vars in our .bashrc
  when: define_oc_env | default(false) | bool
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: "source /root/.oc_env.sh"
    search_string: "source /root/.oc_env.sh"
    insertafter: EOF
    state: present
    backup: true
  tags:
    - always

...
