---

- name: Reload firewall
  ansible.builtin.command:
    cmd: "firewall-cmd --reload"
  failed_when: false
  changed_when: true

- name: Restart Haproxy
  ansible.builtin.systemd:
    name: "{{ haproxy.service }}"
    state: restarted
    daemon_reload: true

- name: Enable and Start Haproxy
  ansible.builtin.systemd:
    name: "{{ haproxy.service }}"
    enabled: true
    state: started
    daemon_reload: true

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

...
